---
- name: Setup Kubernetes Cluster with K3s
  hosts: all
  become: yes
  vars:
    k3s_version: v1.27.4+k3s1
    master_ip: "{{ groups['master'][0] }}"
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name:
          - curl
          - wget
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present

- name: Configure master node
  hosts: master
  become: yes
  tasks:
    - name: Install K3s server
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_KUBECONFIG_MODE="644" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Save token to file
      copy:
        content: "{{ k3s_token.stdout }}"
        dest: /tmp/k3s_token
        mode: 0600

    - name: Copy kubeconfig to local
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ playbook_dir }}/../kubeconfig"
        flat: yes

- name: Configure worker nodes
  hosts: workers
  become: yes
  vars:
    k3s_token: "{{ hostvars['k8s-master']['k3s_token']['stdout'] }}"
  tasks:
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ k3s_token }} INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

- name: Configure kubectl on local machine
  hosts: localhost
  connection: local
  tasks:
    - name: Update kubeconfig with master IP
      replace:
        path: "{{ playbook_dir }}/../kubeconfig"
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ master_ip }}:6443'

    - name: Set KUBECONFIG environment variable
      lineinfile:
        path: ~/.bashrc
        line: 'export KUBECONFIG={{ playbook_dir }}/../kubeconfig'
        state: present